[global/wm]
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/main]
#wm-restack = i3

;; size
top = true
height = 36
width = 100%
offset-x = 0px
offset-y = 0px

border-size = 3px
#border-corlor = ${colors.foreground}
radius = 6

;; colors
background = ${colors.background}
foreground = ${colors.foreground}

;; fonts
font-0 = "JetBrainsMono Nerd Font:style=Medium:size=9;3"
font-1 = "JetBrainsMono Nerd Font:style=Bold:size=9;3"
font-2 = "Font Awesome 6 Free Solid:style=Solid:size=10;3"
font-3 = "Font Awesome 6 Brands Regular:style=Regular:size=10;3"
font-4 = "Font Awesome 6 Free Solid:style=Solid:size=8;2"
line-size = 3

;; modules
fixed-center = true
modules-left = workspaces
modules-center = title
modules-right = alsa redshift tray date power
